# application.yml 编码是 UTF-8
#####################################################################
server:
  # 该项目启动的端口号
  port: 10086
#####################################################################
# Eureka 配置
eureka:
  # 客户端配置
  client:
    # 表示是否将当前模块注册到服务器上，因为该模块是 server，所以不要
    register-with-eureka: false
    # 表示是否获取注册信息
    fetch-registry: false
    # 表示 Eureka 客户端和服务端交互地址
    service-url:
      # 当服务端发布后，Eureka客户端需要向该地址注册
      defaultZone: http://127.0.0.1:${server.port}/eureka/
