# app.yml 编码是 UTF-8
#####################################################################
server:
  # 该项目启动的端口号
  port: 9018
#####################################################################
# log日志等级,mybatis打印sql
logging:
  level:
    com.gsm.dao: DEBUG
#####################################################################
spring:
  # 项目操作
  application:
    # 给项目起个名，注意【使用中划线，下划线SpringCloud不支持】
    name: springcloud-article
  # 数据源
  datasource:
    # 数据源驱动   多个单词之间可以不用中划线，换成大写  【driver-class-name】【driverClassName】
    driver-class-name: com.mysql.jdbc.Driver
    # 数据库url      【时区】serverTimezone=Asia/Shanghai    【连接】useSSL=false&autoReconnect=true   【批量操作】allowMultiQueries=true  【字符编码】characterEncoding=UTF-8
    url: jdbc:mysql://cdb-jwd16kdk.bj.tencentcdb.com:10069/wyxjava?useSSL=false&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    # 数据库用户名
    username: root
    # 数据库用户密码
    password: wyxjava123
  # jpa
  jpa:
    # 数据库类型
    database: mysql
    show-sql: true
  # redis
  redis:
    # 主机ip
    #host: 106.15.238.19
    host: 127.0.0.1
    #端口 不写默认6379
    port: 6379
###########################################################################
# mybatis 框架
mybatis:
  # 别名包
  type-aliases-package: com.gsm.pojo
  # mapper文件位置
  mapper-locations: classpath:com/gsm/dao/*Mapper.xml
  # 配置
  configuration:
    # 数据库列名 user_name 映射pojo userName 格式转换
    map-underscore-to-camel-case: true
###########################################################################
# Eureka 配置
eureka:
  # 客户端配置
  client:
    # 表示是否将当前模块注册到服务器上，因为该模块是 client，所以需要，不写默认 true
    register-with-eureka: true
    # 表示是否获取注册信息，不写默认 true
    fetch-registry: true
    # 表示 Eureka 客户端和服务端交互地址
    service-url:
      # Eureka客户端向该地址注册
      defaultZone: http://127.0.0.1:10086/eureka/
  # 允许各模块跨域访问
  instance:
    prefer-ip-address: true
###########################################################################
# 熔断器 配置
feign:
  hystrix:
    # 开启熔断器
    enabled: true
