# application.yml 编码是 UTF-8
#####################################################################
server:
  # 该项目启动的端口号
  port: 9099
#####################################################################
spring:
  # 项目操作
  application:
    # 给项目起个名，注意【使用中划线，下划线SpringCloud不支持】
    name: springcloud-config
  # 获取配置信息
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wjq303812/wyxjava.git
#####################################################################
# 曝露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh