# application.yml 编码是 UTF-8
#####################################################################
server:
  # 该项目启动的端口号
  port: 9001
#####################################################################
spring:
  # 项目操作
  application:
    # 项目名，使用中划线
    name: springcloud-rabbitmq-producer
  # RabbitMQ 配置
  rabbitmq:
    # ip地址
    host: 106.15.238.19
    # 端口
    port: 5672
#####################################################################
# Eureka 配置
eureka:
  # 客户端配置
  client:
    # 表示是否将当前模块注册到服务器上，因为该模块是 client，所以需要，不写默认 true
    register-with-eureka: true
    # 表示是否获取注册信息，不写默认 true
    fetch-registry: true
    # 表示 Eureka 客户端和服务端交互地址
    service-url:
      # Eureka客户端向该地址注册
      defaultZone: http://127.0.0.1:10086/eureka/
  # 允许各模块跨域访问
  instance:
    prefer-ip-address: true

fanoutexchange:
  name: myFanoutExchange